### PR TITLE
Add some missing fields to story and media

### PR DESCRIPTION
**Pull request by ANaddafi**
I added paid partnership (sponsor_tags) for story and post, comment_disabled (for posts), and story sticker link.

After using lamadava.com services, I realized there are some field which extractors and types in instagrapi client don't support, and thus the Lamadava api doesn't provide them. So I added the fields to "types" and "extractors".

Added fields and types:
- **sponsor_tags** (paid partnership) added to "Story" and "Media"
- **comments_disabled** added to "Media"
- **StoryStickerLink** added to "StorySticker" (story_link field)

### CODE REVIEW

**Comment by adw0rd** [comment]
@ANaddafi thanks!

**Comment by ANaddafi** [comment]
@adw0rd Thank you for your great api client! Will this changes affect lamadava.com responses too? I'm mostly using lamadava services than instagrapi client, so I would appreciate it if lamadava get updated as well.

**Comment by adw0rd** [comment]
@ANaddafi I will do it this week

**Comment by adw0rd** [comment]
@ANaddafi ready on lamadava

**Comment by ANaddafi** [comment]
@adw0rd Thank you. I tried to use Lamadava for story links today, but it didn't work as I expected. I reviewed the code and tested with the client, and realized the graphql story response does not provide story stickers, while private request does. Perhaps lamadava is using gql requests for stories?
Thank you in advance.

**Comment by ANaddafi** [comment]
@adw0rd Could you please check it for me? I can't use Lamadava for stories with link stickers, and it bothers me a bit; so I'd really appreciate it. Thank you in advance.

**Comment by adw0rd** [comment]
@ANaddafi i'll check it today!

**Comment by ANaddafi** [comment]
@adw0rd Any updates?

**Comment by ANaddafi** [comment]
@adw0rd Any Updates?

**Comment by adw0rd** [comment]
@ANaddafi try 
image


https://api.lamadava.com/docs#/%2Fv2%2Fuser/user_stories_v2_user_stories_get

image

**Comment by ANaddafi** [comment]
@adw0rd Thank you! Though I thought the v1 api would get fixed, but this works well for me too! Sorry for the trouble, and thanks again! ;)

**Comment by adw0rd** [comment]
image

Hey, ready for /v1/user/stories

**Comment by ANaddafi** [comment]
@adw0rd Thank yooou!

**Pull request merged**
