### PR TITLE
Attempt to fix select_contact_point_recovery

### PR DESCRIPTION
**Pull request by skords**
Basic hack to fix the issue temporarily

### CODE REVIEW

**Comment by Wathfea** [comment]
@adw0rd is this somehow missed the merge?

**Comment by skords** [comment]
> @adw0rd is this somehow missed the merge?

I closed this myself because it requires an additional API request after email verification which is missing in this commit.

**Comment by Wathfea** [comment]
@skords  Ah I understand, and it is hard to add it, or you are planning to add it in a new PR?

**Comment by windowpane** [comment]
Hey,

I solved the issue of the missing additional API request on my side.. please use the following code for the `challenge.py` file:

``` python
        elif step_name == "select_contact_point_recovery":
            """
                {
                    'step_name': 'select_contact_point_recovery',
                    'step_data': {'choice': '0',
                        'phone_number': '+62 ***-****-**11',
                        'email': 'g*******b@w**.de',
                        'hl_co_enabled': False,
                        'sigp_to_hl': False
                    },
                    'flow_render_type': 3,
                    'bloks_action': 'com.instagram.challenge.navigation.take_challenge',
                    'cni': 178623487724,
                    'challenge_context': '{"step_name": "select_contact_point_recovery",
                    "cni": 178623487724,
                    "is_stateless": false,
                    "challenge_type_enum": "HACKED_LOCK",
                    "present_as_modal": false}',
                    'challenge_type_enum_str': 'HACKED_LOCK',
                    'status': 'ok'
                }
                """
            steps = self.last_json["step_data"].keys()
            challenge_url = challenge_url[1:]
            if "email" in steps:
                self._send_private_request(
                    challenge_url, {"choice": ChallengeChoice.EMAIL})
            elif "phone_number" in steps:
                self._send_private_request(
                    challenge_url, {"choice": ChallengeChoice.SMS})
            else:
                raise ChallengeError(
                    f'ChallengeResolve: Choice "email" or "phone_number" (sms) not available to this account {self.last_json}')
            wait_seconds = 5
            for attempt in range(24):
                code = self.challenge_code_handler(self.username, ChallengeChoice.EMAIL)
                if code:
                    break
                time.sleep(wait_seconds)
            print(f'Code entered "{code}" for {self.username} ({attempt} attempts by {wait_seconds} seconds)')
            self._send_private_request(challenge_url, {"security_code": code})
            # assert 'logged_in_user' in client.last_json
            assert self.last_json.get("action", "") == "close"
            assert self.last_json.get("status", "") == "ok"
            return True
```

**Comment by Wathfea** [comment]
Hey @windowpane  create a pull request for it

**Comment by windowpane** [comment]
Created a pull request: #1225 !

**Pull request closed without merging**
