### PR TITLE
Active presence and Notes update

### PR DESCRIPTION
**Pull request by Yessirskiy**
Minor changes in PR:
1. Fixed type hint of the recently added direct_message_search() (#1521)
2. Added Return description in direct_users_presence() (#1482)
3. Added creator_info() (probably, separated CreatorMixin needed as there are some more /creator/ methods unexplored)

Major changes done in NoteMixin and related:
1. Removed NoteRequest and NoteResponse from types.py. Instead, left just Note class (status field removed as it's only received on creation, indicating success of the action).
2. Remove extract_note() as not a single method requires an extractor.
3. Removed uuid import, as no need in generating one for requesting.
4. Added docs to every single method.
5. Added response parsing: create_note(), get_notes() returning Note and List[Note]; delete_note() + last_seen_update_note() - bool
6. last_seen_update_note() added.
7. Renamed existing methods, previos naming didn't reflect the functionality and looked a bit ugly :) xD

### CODE REVIEW

**Comment by adw0rd** [comment]
@Yessirskiy big thanks!

**Comment by adw0rd** [comment]
@Yessirskiy do you plan to add changes to the documentation?

**Comment by Yessirskiy** [comment]
> @Yessirskiy do you plan to add changes to the documentation?

Yeah, will do on weekends :)

**Comment by adw0rd** [comment]
@Yessirskiy thanks!

**Comment by adw0rd** [comment]
I just noticed such a [PR](https://github.com/adw0rd/instagrapi/pull/1380/files), can you see what is useful there?

**Comment by Yessirskiy** [comment]
> I just noticed such a [PR](https://github.com/adw0rd/instagrapi/pull/1380/files), can you see what is useful there?
> 
> 
> 
> 

Not much really, changed only docs, naming, but not functionality

**Pull request merged**
