### PR TITLE
Add best practices documentation

### PR DESCRIPTION
**Pull request by noqcks**
I noticed there was quite a learning curve for me when using instagrapi for the first time. I had to crawl different GitHub issues, and check the Telegram channel to see what specific errors messages were giving me. 

So I added some best practices documentation, mostly around logging in, proxies, and such.

Hope this helps and will reduce the volume of github issues created with the same question again and again.

### CODE REVIEW

**Comment by adw0rd** [comment]
@noqcks thanks!

**Comment by noqcks** [comment]
https://adw0rd.github.io/instagrapi/best-practices.html gives 404 too

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/best-practices.html

**Comment by noqcks** [comment]
Nice. The link to Best Practices on [this page ](https://adw0rd.github.io/instagrapi/) still returns the .md. Not sure what I have to change here. I have it setup exactly like the links for Development Guide

**Pull request merged**
